version: '3'
services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile-webpack
    volumes:
      - ./web:/usr/src/app
    restart: unless-stopped
    environment:
      - ENV=production
    ports:
      - "8181:8181"
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - mongo
      - nginx
    environment:
      - ENV=prod
      - MAILGUN_PASS=${MAILGUN_PASS}
      - VIRTUAL_HOST=chandler.gangplank.community
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=chandler.gangplank.community
      - LETSENCRYPT_EMAIL=jack@jackketcham.com
    ports:
      - "8000:8000"
  celery:
    build:
      context: .
      dockerfile: Dockerfile-server
    command: celery worker --loglevel info --app gangplank.celery
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - server
      - rabbit
    environment:
      - ENV=prod
      - MAILGUN_PASS=${MAILGUN_PASS}
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile-server
    command: celery beat --loglevel info --app gangplank.celery
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - server
      - rabbit
  mongo:
    image: "mongo:3.4.5"
    restart: unless-stopped
  rabbit:
    image: "rabbitmq:3.6-management-alpine"
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    restart: unless-stopped
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/certs:/etc/nginx/certs:ro
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
